### ISSUE TITLE
Double licensing?

### ISSUE THREAD

**Issue by rpsu** [City-of-Turku/kada#12]
> The project is licensed under the same license as Drupal itself, namely GNU General Public License 2 or later.
> 
> KADA Drupal distribution. Copyright © 2017 City of Turku, http://www.turku.fi/, turun.kaupunki@turku.fi

Can you clarify this double licensing? What parts are actually (c) if everything is GPL, too?

**Comment by ZeiP** [comment]
The [GNU guide to using GPL](https://www.gnu.org/licenses/gpl-howto.html) suggests using a copyright statement in addition to the license statement, because the license might not be enforceable by others than the copyright holder. That's why there is a copyright statement also. The license statement is not meant to rule any parts of the distribution outside the GPL license.
