### ISSUE TITLE
Dev environment?

### ISSUE THREAD

**Issue by back-2-95** [City-of-Turku/kada#17]
Documentation mentions Vagrant but there is no Vagrantfile but there is docker-compose.yml file without any mention in the documentation?

How should one setup local developing environment?

**Comment by ZeiP** [comment]
The Vagrantfile mentioned is in a separate project repository that hasn't been opened, since it hasn't been deemed very useful and probably requires quite a lot more maintenance.

Basically you can run the Drupal platform on any Drupal-compatible environment; quite a few of us use the Docker solution in https://github.com/CitrusSolutions/docker-php/tree/stable and the original Vagrant build is based on (but is not the same as) https://github.com/wunderkraut/WunderTools.

We'll try to clarify this in the README better.

**Comment by ZeiP** [comment]
Committed a change for README to clarify the development environment situation in PR https://github.com/DigiTurku/kada/pull/19
